#!/usr/bin/env bash


# Shortcuts

alias reload="source ~/.bash_profile"

# ls Command
LS_COMMON="-hGp"
# --color : On Windows7 this produces permission errors, e.g. for Music folder:
LS_COMMON="$LS_COMMON --color=auto "
LS_COMMON="$LS_COMMON -I NTUSER.DAT\* -I ntuser.dat\* "
# LS_COMMON="$LS_COMMON -I AppData\*"
# LS_COMMON="$LS_COMMON -I Music\*"
# LS_COMMON="$LS_COMMON -I Pictures\*"
# LS_COMMON="$LS_COMMON -I Start\ Menu\*"
# LS_COMMON="$LS_COMMON -I Application\ Data\*"
# LS_COMMON="$LS_COMMON -I Local\ Settings\*"
# LS_COMMON="$LS_COMMON -I Cookies\*"
LS_COMMON="$LS_COMMON -I ntuser.ini "
LS_COMMON="$LS_COMMON -I ntuser.pol "
LS_COMMON="$LS_COMMON -I Thumbs.db "
# LS_COMMON="$LS_COMMON -I Favorites\*"
# LS_COMMON="$LS_COMMON -I Recent\*"
# LS_COMMON="$LS_COMMON -I Searches\*"
# LS_COMMON="$LS_COMMON -I Videos\*"
# LS_COMMON="$LS_COMMON -I Desktop\*"
alias ls="command ls $LS_COMMON" # Windows git bash

mk () {
    mkdir -p "$@" && cd -P "$@"
}

# Wrapper function for Maven's mvn command.
mvn-color()
{
  # Filter mvn output using sed
  mvn $@ | sed -e "s/\(\[INFO\]\ \-.*\)/${BOLD}\1${RESET_FORMATTING}/g" \
               -e "s/\(\[INFO\]\ \[.*\)/${RESET_FORMATTING}${BOLD}\1${RESET_FORMATTING}/g" \
               -e "s/\(\[INFO\]\ BUILD SUCCESSFUL\)/${BOLD}${TEXT_GREEN}\1${RESET_FORMATTING}/g" \
               -e "s/\(\[debug\].*\)/${TEXT_CYAN}\1${RESET_FORMATTING}/g" \
               -e "s/\(\[WARNING\].*\)/${BOLD}${TEXT_YELLOW}\1${RESET_FORMATTING}/g" \
               -e "s/\(\[ERROR\].*\)/${BOLD}${TEXT_RED}\1${RESET_FORMATTING}/g" \
               -e "s/Tests run: \([^,]*\), Failures: \([^,]*\), Errors: \([^,]*\), Skipped: \([^,]*\)/${BOLD}${TEXT_GREEN}Tests run: \1${RESET_FORMATTING}, Failures: ${BOLD}${TEXT_RED}\2${RESET_FORMATTING}, Errors: ${BOLD}${TEXT_RED}\3${RESET_FORMATTING}, Skipped: ${BOLD}${TEXT_YELLOW}\4${RESET_FORMATTING}/g"
  MVN_EXIT=${PIPESTATUS[0]}
  # Make sure formatting is reset
  echo -ne ${RESET_FORMATTING}
  return ${MVN_EXT}
}

# Override the mvn command with the colorized one.
alias mvnc="mvn-color"

alias vimwiki="vim +VimwikiIndex"
alias note="vim +Note"
alias notes="vim +Notes"
alias in="task add +in"

#list declared aliases, functions, paths

alias aliases="alias | sed 's/=.*//'"
alias functions="declare -f | grep '^[a-z].* ()' | sed 's/{$//'"
alias paths='echo -e ${PATH//:/\\n}'
