#!/usr/bin/env bash


# Shortcuts

alias reload="source ~/.bash_profile"

# ls Command
LS_COMMON="-hGp"
# --color : On Windows7 this produces permission errors, e.g. for Music folder:
LS_COMMON="$LS_COMMON --color=auto "
LS_COMMON="$LS_COMMON -I NTUSER.DAT\* -I ntuser.dat\* "
# LS_COMMON="$LS_COMMON -I AppData\*"
# LS_COMMON="$LS_COMMON -I Music\*"
# LS_COMMON="$LS_COMMON -I Pictures\*"
# LS_COMMON="$LS_COMMON -I Start\ Menu\*"
# LS_COMMON="$LS_COMMON -I Application\ Data\*"
# LS_COMMON="$LS_COMMON -I Local\ Settings\*"
# LS_COMMON="$LS_COMMON -I Cookies\*"
LS_COMMON="$LS_COMMON -I ntuser.ini "
LS_COMMON="$LS_COMMON -I ntuser.pol "
LS_COMMON="$LS_COMMON -I Thumbs.db "
# LS_COMMON="$LS_COMMON -I Favorites\*"
# LS_COMMON="$LS_COMMON -I Recent\*"
# LS_COMMON="$LS_COMMON -I Searches\*"
# LS_COMMON="$LS_COMMON -I Videos\*"
# LS_COMMON="$LS_COMMON -I Desktop\*"
alias ls="command ls $LS_COMMON" # Windows git bash

# grep
GREP_COMMON="--color=auto"
alias grep="command grep $GREP_COMMON"


alias mvnc="mvn-color" # Colorized maven

# Vim related
alias vimwiki="vim +VimwikiIndex" # open vim wiki page
alias note="vim +Note" # open Vim to a new note in vim wiki
alias notes="vim +Notes" # open vim wiki to notes page

alias in="task add +in" # add a new task in taskwarrior with the category of in

#list declared aliases, functions, paths

alias aliases="alias | sed -r 's/alias ([^=]*)=.*/\1/'" # list out all aliases
alias functions="declare -f | grep '^[a-z].* ()' | sed 's/{$//'" # list the content of all custom functions
alias paths='echo -e ${PATH//:/\\n}' # list all paths on the $PATH
alias dhelp="grep "^function" ~/.bash/rc/functions | sed 's/function/+/g' | sed 's/() #/ - /g'" # display function summaries

